# Generated by Django 5.0.1 on 2024-01-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0002_address_basket_bill_delivery_deliverystate_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
