# Generated by Django 5.0.1 on 2024-01-30 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_app', '0005_alter_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='po_app.bill'),
        ),
    ]
